name: macOS VM with Zrok Tunnel

on:
  workflow_dispatch

jobs:
  setup-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Remove conflicting packages
      run: |
        sudo apt-get remove -y containerd docker.io docker-compose || true
        sudo apt-get autoremove -y

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose git

    - name: Clone macOS project
      run: git clone https://github.com/dockur/macos.git

    - name: Modify compose.yml version
      run: |
        cd macos
        sed -i 's/VERSION: "13"/VERSION: "14"/' compose.yml

    - name: Start Docker containers
      run: |
        cd macos
        sudo docker-compose up -d

    - name: Wait for services to start
      run: sleep 30

    - name: Install Zrok
      run: curl -sSf https://get.openziti.io/install.bash | sudo bash -s zrok

    - name: Setup Zrok environment
      run: sudo zrok enable ${{ secrets.ZROK_ENV_TOKEN }}

    - name: Share public port
      run: sudo zrok share public localhost:8006 &

    - name: Share private port
      run: sudo zrok share private --backend-mode tcpTunnel localhost:5900 &

    - name: Wait for 6 hours
      run: sleep 21600