name: macOS VM with Zrok Tunnel

on:
  workflow_dispatch

jobs:
  setup-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose git

    - name: Clone macOS project
      run: git clone https://github.com/dockur/macos.git

    - name: Modify compose.yml version
      run: sed -i 's/VERSION: "13"/VERSION: "14"/' macos/compose.yml

    - name: Start Docker containers
      run: |
        cd macos
        sudo docker-compose up -d

    - name: Wait for services to start
      run: sleep 30

    - name: Install and setup Zrok
      run: |
        curl -sSf https://get.openziti.io/install.bash | sudo bash -s zrok
        sudo zrok enable ${{ secrets.ZROK_ENV_TOKEN }}
        sudo zrok share public localhost:8006 &
        sudo zrok share private --backend-mode tcpTunnel localhost:5900 &
        sleep 6h
        sudo pkill zrok

    - name: Cleanup
      run: |
        cd macos
        sudo docker-compose down
